
 platform :ios, '9.0'

target 'LRLoopScrollViewTest' do
  
  use_frameworks!

  #  pod 'RxSwift',    '~> 4.0'
  #  pod 'RxCocoa',    '~> 4.0'
  #  pod 'RxDataSources'
  #  pod 'ReactorKit'
  # pod 'Kingfisher', '~> 4.0'
  
 pod 'LRLoopScrollView', :git => 'https://github.com/peiei/LoopScrollView.git'


end
